# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-05-28 15:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_banner_emailverifyrecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(choices=[('male', '男'), ('female', '女')], default='', max_length=6, verbose_name='性别'),
        ),
    ]
